### PR TITLE
Replace `gopkg.in/yaml.v2` with `gopkg.in/yaml.v3`

### PR DESCRIPTION
**Pull request by Juneezee**
Right now, we are using two YAML packages
1. gopkg.in/yaml.v2
2. gopkg.in/yaml.v3

We can keep only the latest `gopkg.in/yaml.v3` package.

### CODE REVIEW

**Review by didrocks — DISMISSED** [review]
Thanks a lot for contributing to adsys, and nicely spotted!

We will still need yamlv2 as part of indirect of our vendored dependencies, but that makes it more consistent.

Thanks again! Approving and merging.

**Comment by didrocks** [comment]
Do you mind refreshing the golden files yourself in the 2 directories you are changing the dep version (deserizalizing of yaml changed)? (Otherwise, I can PR against your branch so that you merge it).

What you need to do should something along those lines:
```sh
$ cd internal/watchdtui) && go test -update
$ cd ../config/watchd && go test -update
```

Then, commit the changes in the `golden/` directories in a separate commit. Those should only have formatting difference.

Thanks!

**Comment by Juneezee** [comment]
> Do you mind refreshing the golden files yourself in the 2 directories you are changing the dep version (deserizalizing of yaml changed)? (Otherwise, I can PR against your branch so that you merge it).
> 
> What you need to do should something along those lines:
> 
> ```shell
> $ cd internal/watchdtui) && go test -update
> $ cd ../config/watchd && go test -update
> ```
> 
> Then, commit the changes in the `golden/` directories in a separate commit. Those should only have formatting difference.
> 
> Thanks!

@didrocks Thanks for reviewing this PR. I have updated the golden files. Please take a look again.

**Review by didrocks — APPROVED** [review]
@Juneezee: thanks for your quick feedback! It looks good. Let me rerun the CI now and everything should be good :)

**Comment by didrocks** [comment]
As GitHub CI seems to be down, I did rerun it locally and it passes, thanks a lot! Merging.

**Comment by Juneezee** [comment]
@didrocks This commit https://github.com/ubuntu/adsys/commit/6c457685ca6b09daa2b7d1483a6e3ba5d1c3959d was merged an hour ago and another `"gopkg.in/yaml.v2"` slipped in :sweat_smile: . Sorry I didn't notice this

**Pull request merged**
