### PR TITLE
ci(docs): generate documentation from policy definition

### PR DESCRIPTION
**Pull request by didrocks**
Generate within CI the whole documentation for supported policies

------
UDENG-1450

### CODE REVIEW

**Comment by didrocks** [comment]
waiting for the other documentation related PRs to be merged first before rebasing so that tests pass.

**Comment by didrocks** [comment]
@jibel: And the final piece, the icing on the cake!
Note that only https://github.com/ubuntu/adsys/pull/849/commits/006322ffd1bc6cf3eae3cbc5e55ce7723771f717, https://github.com/ubuntu/adsys/pull/849/commits/2cbc0e581021d99d43f1018bf8b847f7fa6b69ff and https://github.com/ubuntu/adsys/pull/849/commits/fb34abe13074fce7cd032e7fc0680a2b8a3729cf are the actual commits, the generated PR with the content has been triggered as PR #851 and was merged in after checking.

**Review by jibel — APPROVED** [review]
Good YAML programming skills :)

**Review by jibel — APPROVED** [review]
Trivial. Thanks!

**Pull request merged**
